---
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.3

suites:
  - name: kube-master
    driver:
      network:
        - ["private_network", {ip: "192.168.7.10"}]
    run_list: chef-kubernetes::kube_master
  - name: kube-worker
    driver:
      network:
        - ["private_network", {ip: "192.168.7.11"}]
    run_list: chef-kubernetes::kube_worker

